#!/bin/sh

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "Initialising submodules"
yadm submodule update --recursive --init

# Complete .tmux configuration setup
ln -s -f .tmux/.tmux.conf

# Complete pyenv-virtualenv setup
ln -s -f $(pwd)/.pyenv-virtualenv .pyenv/plugins/pyenv-virtualenv
